name: Release

on:
  push:
    branches: [main, next, next-setup]
permissions:
  id-token: write
  contents: write

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version: ["22.x", "24.x", "26.x"]

    name: Test on Node ${{ matrix.node-version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Set up Docker
        uses: docker/setup-buildx-action@v4

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Run integration tests
        env:
          SKIP_TEARDOWN: false
          REUSE_CONTAINER: false
          NODE_ENV: test
          FUSIONAUTH_TELEMETRY: false
        run: npm test
        timeout-minutes: 15

  release:
    name: Release
    needs: test
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: /usr/bin/bash -l -e -o pipefail {0}
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 22.x
          registry-url: "https://registry.npmjs.org"

      - name: Install dependencies
        run: npm ci

      - name: Install semantic-release extra plugins
        run: npm install --save-dev @semantic-release/changelog @semantic-release/git

      # - name: Lint
      #   run: npm run lint-fix

      - name: Build
        run: npm run build

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release
